#!/bin/bash

set -e

if [[ -z "$*" ]] ; then
    echo "Usage: $0 <pubkey>"
    echo "    $0 ssh-ed25519 AAA..."
    exit 1
fi

NPIPERELAY=$(which npiperelay.exe)

if [[ -z "$NPIPERELAY" ]] ; then
    echo "Please install npiperelay.exe on Windows and set PATH"
    exit 1
fi

if [[ ! "$NPIPERELAY" == /usr/local/bin/* ]] ; then
    echo "symlink..."
    sudo ln -sf $(which npiperelay.exe) /usr/local/bin
fi

echo "systemd unit..."
systemctl --user daemon-reload
systemctl --user enable --now win-ssh-agent.socket

echo "git config..."
git config --global gpg.format ssh
git config --global user.signingkey "$*"
git config --global commit.gpgsign true
git config --global tag.gpgsign true
