#!/bin/bash

set -e

cat << EOF
Available scripts:
    sarisia_authkey: sync ~/.ssh/authorized_keys to github.com/sarisia.keys
    sarisia_dotfiles: update dotfiles
    sarisia_homebrew: install homebrew
    sarisia_ssh_agent_win: setup ssh-agent forwarding from Windows
EOF
